--테이블삭제

DROP TABLE "BAD_CNT";
DROP TABLE "GOOD_CNT";
DROP TABLE "REV_IMG";
DROP TABLE "REVIEW";
DROP TABLE "PLACE_BOOKMARK";
DROP TABLE "CHARGE";
DROP TABLE "OPE";
DROP TABLE "DES_IMG";
DROP TABLE "PLACE_INFO";
DROP TABLE "PLACE";
DROP TABLE "USER_INFO";
DROP TABLE "CAR_INFO_TABLE";


--테이블생성

CREATE TABLE "CAR_INFO_TABLE" (
	"CAR_MODEL"	VARCHAR2(100)		NOT NULL,
	"COP"	VARCHAR2(31)		NOT NULL,
	"FUEL"	VARCHAR2(20)		NOT NULL,
	"MPG"	VARCHAR2(20)		NOT NULL,
	"VOL"	NUMBER          NULL,
	"GEAR"	VARCHAR2(12)		NOT NULL,
	"CAR_LEVEL"	VARCHAR2(20)		NOT NULL,
	"CAR_CO2"	NUMBER		NOT NULL,
	"CAR_TYPE"	VARCHAR2(20)		NOT NULL
);
CREATE TABLE "USER_INFO" (
	"ID"	VARCHAR2(20)		NOT NULL,
	"PWD"	VARCHAR2(150)		NOT NULL,
	"NAME"	VARCHAR2(10)		NOT NULL,
	"EMAIL"	VARCHAR2(20)		NOT NULL,
    "HND_NO"    VARCHAR2(11)		NOT NULL,
    "POST_NO"	VARCHAR2(5)		NOT NULL,
	"ADD1"	VARCHAR2(100)		NOT NULL,
	"ADD2"	VARCHAR2(30)		NULL,
    "AGREE1"	VARCHAR2(1)		NOT NULL,
    "AGREE2"	VARCHAR2(1)		NOT NULL,
    "AGREE3"	VARCHAR2(1)		NOT NULL,
    "CAR_MODEL"	VARCHAR2(100)		NOT NULL
);
CREATE TABLE "PLACE" (
	"PLACE_NO"	NUMBER		NOT NULL,
	"PLACE_TYPE"	VARCHAR2(20)		NOT NULL
);
CREATE TABLE "PLACE_INFO" (
	"P_NO"	VARCHAR2(20)		NOT NULL,
	"P_NAME"	VARCHAR2(111)		NOT NULL,
	"P_ROAD_NO"	VARCHAR2(100)		NULL,
	"P_ADDRESS"	VARCHAR2(100)		NULL,
	"P_INFO"	VARCHAR2(500)		NULL,
	"P_TYPE"	VARCHAR2(10)	NOT NULL,
	"P_VAL"	VARCHAR2(10)		NOT NULL,
	"P_NUMBER"	NUMBER		NULL,
	"P_UNIT"	VARCHAR2(10)	NULL,
    "PLACE_NO"	NUMBER		    NULL
);
COMMENT ON COLUMN "PLACE_INFO"."P_UNIT" IS '대,명,테이블';
CREATE TABLE "DES_IMG" (
	"DES_IMG_FILE"	VARCHAR2(250)		NOT NULL,
	"P_NO"	VARCHAR2(20)		NOT NULL
);
CREATE TABLE "OPE" (
	"P_NO"	VARCHAR2(20)		NOT NULL,
	"P_DAY"	VARCHAR2(30)		NOT NULL,
	"P_WEEKDAY_STARTTIME"	VARCHAR2(5)		NOT NULL,
	"P_WEEKDAY_ENDTIME"	VARCHAR2(8)		NOT NULL,
	"P_SAT_STARTTIME"	VARCHAR2(5)		NULL,
	"P_SAT_ENDTIME"	VARCHAR2(8)		NULL,
	"P_WEEKEND_STARTTIME"	VARCHAR2(5)		NULL,
	"P_WEEKEND_ENDTIME"	VARCHAR2(8)		NULL
);
CREATE TABLE "CHARGE" (
	"P_NO"	VARCHAR2(20)		NOT NULL,
	"P_CHARGE_INFO"	VARCHAR2(30)		NOT NULL,
	"P_BASIC_TIME"	NUMBER		NULL,
	"P_BASIC_CHARGE"	NUMBER		NULL,
	"P_MORE_TIME"	NUMBER		NULL,
	"P_MORE_CHARGE"	VARCHAR2(10)	NULL,
	"P_DAY_TIME"	NUMBER		NULL,
	"P_DAY_CHARGE"	NUMBER		NULL,
	"P_WEEK_CHARGE"	NUMBER		NULL,
	"P_CHARGE_METHOD"	VARCHAR2(35)		NULL
);
COMMENT ON COLUMN "CHARGE"."P_CHARGE_INFO" IS '무료, 유료';
CREATE TABLE "PLACE_BOOKMARK" (
	"ID"	VARCHAR2(20)		NOT NULL,
	"P_NO"	VARCHAR2(20)		NOT NULL
);
CREATE TABLE "REVIEW" (
	"R_NO"	NUMBER(10)		NOT NULL,
	"P_NO"	VARCHAR2(20)		NOT NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NOT NULL,
	"RDATE"	VARCHAR2(20)		NOT NULL,
	"R_STAR"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);
COMMENT ON COLUMN "REVIEW"."R_STAR" IS '1~5중선택';
COMMENT ON COLUMN "REVIEW"."ID" IS '후기쓴회원';
CREATE TABLE "REV_IMG" (
	"REV_IMG_FILE"	VARCHAR2(250)		NOT NULL,
	"R_NO"	NUMBER(10)		NOT NULL
);
CREATE TABLE "GOOD_CNT" (
	"R_NO"	NUMBER(10)		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);
COMMENT ON COLUMN "GOOD_CNT"."ID" IS '좋아요누른회원';
CREATE TABLE "BAD_CNT" (
	"R_NO"	NUMBER(10)		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL
);
COMMENT ON COLUMN "BAD_CNT"."ID" IS '싫어요를누른회원';