-- CAR_INFO_TABLE 중복행 제거
DELETE FROM CAR_INFO_TABLE T3
    WHERE T3.ROWID IN (
    SELECT T2.RID
    FROM ( 
        SELECT T1.CAR_MODEL, COUNT(*) OVER(PARTITION BY CAR_MODEL) AS OVERLAP,
            T1.ROWID AS RID,
            ROW_NUMBER() OVER(PARTITION BY T1.CAR_MODEL ORDER BY T1.ROWID DESC) AS RN
        FROM CAR_INFO_TABLE T1) T2
    WHERE T2.RN > 1
    )
;
COMMIT;